# Generated by Django 3.2.9 on 2021-12-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211202_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hours',
            field=models.TimeField(verbose_name='Consulting Hours : e.g. (10 AM - 1 PM)'),
        ),
    ]
