# Generated by Django 3.2.9 on 2021-12-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211202_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hours',
            field=models.DateTimeField(default='2021-12-02 18:29'),
        ),
    ]
