# Generated by Django 3.2.9 on 2021-12-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hours',
        ),
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.TimeField(default='3:00', verbose_name='Chamber Ending Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.TimeField(default='12:00', verbose_name='Chamber Beginning Time'),
            preserve_default=False,
        ),
    ]
