# Generated by Django 3.2.9 on 2021-12-02 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overall_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
