# Generated by Django 3.2.9 on 2021-12-05 15:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '  Monday'), (1, '  Tuesday'), (2, '  Wednesday'), (3, '  Thursday'), (4, '  Friday'), (5, '  Saturday'), (6, '  Sunday')], max_length=13, verbose_name='Available Days'),
        ),
    ]
