# Generated by Django 3.1.12 on 2021-12-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20211212_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ji',
            field=models.CharField(default='Jio', max_length=200),
            preserve_default=False,
        ),
    ]
